name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce.
  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: e.g. 93dc1dd
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Include logs/error output.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      placeholder: |
        1) ...
        2) ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: OS, Node version
    validations:
      required: false
